config/routes.rb
ActiveSupport::Inflector.inflections do |inflect|
	inflect.irregular 'bonus', 'bonuses'
end

Org::Application.routes.draw do
  resources :stats

  resources :unavailable_players

  resources :disabled_players

  resources :players

  resources :teams

  resources :leagues

  resources :franchises

	root 'franchises#index'

  

end

app/models/disabled_player.rb
class DisabledPlayer < ActiveRecord::Base
  belongs_to :franchise
  belongs_to :player
	
	scope :current, -> { where('end_date is null') }
end

app/controllers/disabled_players_controller.rb
class DisabledPlayersController < ApplicationController
  before_action :set_disabled_player, only: [:show, :edit, :update, :destroy]

  # GET /disabled_players
  # GET /disabled_players.json
  def index
    @disabled_players = DisabledPlayer.all
  end

  # GET /disabled_players/1
  # GET /disabled_players/1.json
  def show
  end

  # GET /disabled_players/new
  def new
    @disabled_player = DisabledPlayer.new
  end

  # GET /disabled_players/1/edit
  def edit
  end

  # POST /disabled_players
  # POST /disabled_players.json
  def create
    @disabled_player = DisabledPlayer.new(disabled_player_params)

    respond_to do |format|
      if @disabled_player.save
        format.html { redirect_to @disabled_player, notice: 'Disabled player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @disabled_player }
      else
        format.html { render action: 'new' }
        format.json { render json: @disabled_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disabled_players/1
  # PATCH/PUT /disabled_players/1.json
  def update
    respond_to do |format|
      if @disabled_player.update(disabled_player_params)
        format.html { redirect_to @disabled_player, notice: 'Disabled player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @disabled_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disabled_players/1
  # DELETE /disabled_players/1.json
  def destroy
    @disabled_player.destroy
    respond_to do |format|
      format.html { redirect_to disabled_players_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disabled_player
      @disabled_player = DisabledPlayer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disabled_player_params
      params.require(:disabled_player).permit(:franchise_id, :player_id, :year, :length, :start_date, :end_date, :reason, :rehab)
    end
end

app/helpers/disabled_players_helper.rb
module DisabledPlayersHelper
end

app/views/disabled_players/_form.html.erb
<%= form_for(@disabled_player) do |f| %>
  <% if @disabled_player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disabled_player.errors.count, "error") %> prohibited this disabled_player from being saved:</h2>

      <ul>
      <% @disabled_player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :franchise %><br>
    <%= f.text_field :franchise %>
  </div>
  <div class="field">
    <%= f.label :player %><br>
    <%= f.text_field :player %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.number_field :length %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_area :reason %>
  </div>
  <div class="field">
    <%= f.label :rehab %><br>
    <%= f.check_box :rehab %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/disabled_players/edit.html.erb
<h1>Editing disabled_player</h1>

<%= render 'form' %>

<%= link_to 'Show', @disabled_player %> |
<%= link_to 'Back', disabled_players_path %>

app/views/disabled_players/index.html.erb
<h1>Listing disabled_players</h1>

<table>
  <thead>
    <tr>
      <th>Franchise</th>
      <th>Player</th>
      <th>Year</th>
      <th>Length</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Reason</th>
      <th>Rehab</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @disabled_players.each do |disabled_player| %>
      <tr>
        <td><%= disabled_player.franchise %></td>
        <td><%= disabled_player.player %></td>
        <td><%= disabled_player.year %></td>
        <td><%= disabled_player.length %></td>
        <td><%= disabled_player.start_date %></td>
        <td><%= disabled_player.end_date %></td>
        <td><%= disabled_player.reason %></td>
        <td><%= disabled_player.rehab %></td>
        <td><%= link_to 'Show', disabled_player %></td>
        <td><%= link_to 'Edit', edit_disabled_player_path(disabled_player) %></td>
        <td><%= link_to 'Destroy', disabled_player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Disabled player', new_disabled_player_path %>

app/views/disabled_players/new.html.erb
<h1>New disabled_player</h1>

<%= render 'form' %>

<%= link_to 'Back', disabled_players_path %>

app/views/disabled_players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Franchise:</strong>
  <%= @disabled_player.franchise %>
</p>

<p>
  <strong>Player:</strong>
  <%= @disabled_player.player %>
</p>

<p>
  <strong>Year:</strong>
  <%= @disabled_player.year %>
</p>

<p>
  <strong>Length:</strong>
  <%= @disabled_player.length %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @disabled_player.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @disabled_player.end_date %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @disabled_player.reason %>
</p>

<p>
  <strong>Rehab:</strong>
  <%= @disabled_player.rehab %>
</p>

<%= link_to 'Edit', edit_disabled_player_path(@disabled_player) %> |
<%= link_to 'Back', disabled_players_path %>