config/routes.rb
ActiveSupport::Inflector.inflections do |inflect|
	inflect.irregular 'bonus', 'bonuses'
end

Org::Application.routes.draw do
  resources :stats

  resources :unavailable_players

  resources :disabled_players

  resources :players

  resources :teams

  resources :leagues

  resources :franchises

	root 'franchises#index'

  

end

app/models/stat.rb
class Stat < ActiveRecord::Base
  belongs_to :player
  belongs_to :team
  belongs_to :stat_definition
	
	scope :by_player, ->(p) { where{ (player_id == p) } }
	scope :by_year, ->(y) { where{ (season == y) } }
	scope :by_stint, ->(s) { where{ (stint == s) } }
	scope :by_team, ->(t) { where{ (team_id == t.id)}}
	scope :by_level, ->(l) { joins(team: :league).where{("leagues.level = '#{l}'")} }
	scope :by_franchise, ->(f) { joins(team: :franchise).where{(franchise = f)}}
	scope :batting, -> { joins(:stat_definition).where("stat_definitions.category = ?", 'batting') }
	scope :pitching, -> { joins(:stat_definition).where("stat_definitions.category = ?", 'pitching') }
	scope :baserunning, -> { joins(:stat_definition).where("stat_definitions.category = ?", 'baserunning') }
	scope :defense, -> { joins(:stat_definition).where("stat_definitions.category = ?", 'defense') }
	scope :levels, ->(y) { by_year(y).joins(team: :league).select(leagues: :level).distinct }
	
	def format
		puts "formatting..."
		sprintf(stat_definition.format, value)
	end
	
	def self.highest_level_stats(year)
		levels_by_rank = {'MLB' => 0, 'AAA' => 1, 'AA' => 2, 'A+' => 3, 'A' => 4, 'A-SS' => 5, 'R' => 6}
		highest_level = 'R'
		self.levels(year).each do |stat|
			if levels_by_rank[stat.level] < levels_by_rank[highest_level]
				highest_level = stat.level
			end
		end
		self.by_year(year).by_level(highest_level)
	end
	
	
		
	
	
	
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_action :set_stat, only: [:show, :edit, :update, :destroy]

  # GET /stats
  # GET /stats.json
  def index
    @stats = Stat.all
  end

  # GET /stats/1
  # GET /stats/1.json
  def show
  end

  # GET /stats/new
  def new
    @stat = Stat.new
  end

  # GET /stats/1/edit
  def edit
  end

  # POST /stats
  # POST /stats.json
  def create
    @stat = Stat.new(stat_params)

    respond_to do |format|
      if @stat.save
        format.html { redirect_to @stat, notice: 'Stat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stat }
      else
        format.html { render action: 'new' }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stats/1
  # PATCH/PUT /stats/1.json
  def update
    respond_to do |format|
      if @stat.update(stat_params)
        format.html { redirect_to @stat, notice: 'Stat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stats/1
  # DELETE /stats/1.json
  def destroy
    @stat.destroy
    respond_to do |format|
      format.html { redirect_to stats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stat
      @stat = Stat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stat_params
      params.require(:stat).permit(:player_id, :team_id, :stat_definition_id, :season, :stint, :value)
    end
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/stats/_form.html.erb
<%= form_for(@stat) do |f| %>
  <% if @stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stat.errors.count, "error") %> prohibited this stat from being saved:</h2>

      <ul>
      <% @stat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player %><br>
    <%= f.text_field :player %>
  </div>
  <div class="field">
    <%= f.label :team %><br>
    <%= f.text_field :team %>
  </div>
  <div class="field">
    <%= f.label :stat_definition %><br>
    <%= f.text_field :stat_definition %>
  </div>
  <div class="field">
    <%= f.label :season %><br>
    <%= f.number_field :season %>
  </div>
  <div class="field">
    <%= f.label :stint %><br>
    <%= f.number_field :stint %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stats/edit.html.erb
<h1>Editing stat</h1>

<%= render 'form' %>

<%= link_to 'Show', @stat %> |
<%= link_to 'Back', stats_path %>

app/views/stats/index.html.erb
<h1>Listing stats</h1>

<table>
  <thead>
    <tr>
      <th>Player</th>
      <th>Team</th>
      <th>Stat definition</th>
      <th>Season</th>
      <th>Stint</th>
      <th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stats.each do |stat| %>
      <tr>
        <td><%= stat.player %></td>
        <td><%= stat.team %></td>
        <td><%= stat.stat_definition %></td>
        <td><%= stat.season %></td>
        <td><%= stat.stint %></td>
        <td><%= stat.value %></td>
        <td><%= link_to 'Show', stat %></td>
        <td><%= link_to 'Edit', edit_stat_path(stat) %></td>
        <td><%= link_to 'Destroy', stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stat', new_stat_path %>

app/views/stats/new.html.erb
<h1>New stat</h1>

<%= render 'form' %>

<%= link_to 'Back', stats_path %>

app/views/stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player:</strong>
  <%= @stat.player %>
</p>

<p>
  <strong>Team:</strong>
  <%= @stat.team %>
</p>

<p>
  <strong>Stat definition:</strong>
  <%= @stat.stat_definition %>
</p>

<p>
  <strong>Season:</strong>
  <%= @stat.season %>
</p>

<p>
  <strong>Stint:</strong>
  <%= @stat.stint %>
</p>

<p>
  <strong>Value:</strong>
  <%= @stat.value %>
</p>

<%= link_to 'Edit', edit_stat_path(@stat) %> |
<%= link_to 'Back', stats_path %>